### ISSUE TITLE
wlan1 "No such device"

### ISSUE THREAD

**Issue by Taknamay** [samyk/skyjack#4]
Hello. I have installed aircrack-ng from subversion, compiled and updated. I installed node-ar-drone with npm. However, when running your program on Ubuntu I get this error message:

    wlan1: ERROR while getting interface flags: No such device

I am doing this for an undergraduate research project. Your help is appreciated.

**Comment by samyk** [comment]
Pass in wlan0 as the first two arguments to use the same device for everything or add a 2nd wifi interface
