### ISSUE TITLE
some questions in skyjack.pl

### ISSUE THREAD

**Issue by StudentOfHeisenberg** [samyk/skyjack#7]
the codes are excellent, but I can't understand this part 

'		# show user APs
		eval {
			local $SIG{INT} = sub { die };
			my $pid = open(DUMP, "|sudo $airodump --output-format csv -w $tmpfile $interface >>/dev/null 2>>/dev/null") || die "Can't run airodump ($airodump): $!";
			print "pid $pid\n";
			# wait 5 seconds then kill
			sleep 2;
			print DUMP "\cC";
			sleep 1;
			sudo("kill", $pid);
			sleep 1;
			sudo("kill", "-HUP", $pid);
			sleep 1;
			sudo("kill", "-9", $pid);
			sleep 1;
			sudo("killall", "-9", $aireplay, $airodump);
			#kill(9, $pid);
			close(DUMP);
		};`
**I knew that 'open' function could only return 0 or 1, so which process $pid belongs to?
why kill $pid 3 times? and why kill aireplay and airodump?**

**Comment by samyk** [comment]
open returns the process ID when using "|" to execute something. `perldoc -f open`

**Comment by samyk** [comment]
The kills are there just to ensure it exited (first, try to kill politely, then force kill). No need to run aireplay/airodump at this point -- we only want a few seconds of data to capture the MAC.
